[package]
name = "encryption"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0"
rand = "0.8.5"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tracing = "0.1"
x25519-dalek = "2.0"
aes-gcm = "0.10.3"
chacha20poly1305 = "0.10.1" 